name: Test Build

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check if build was successful
        id: check-build
        uses: actions/github-script@v4
        
      - name: Run tests if build was successful
        if: ${{ needs.build.outputs.build-conclusion == 'success' }}
        run: npm run test
